using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TownBossTriggerEvent : AbstractEventController {
	public Sprite baddieHead;
	public Sprite orcHead;
	public GameObject baddie;
	public GameObject orc1;
	public GameObject orc2;
	public GameObject orc3;
	public GameObject orc4;
	public GameObject orc5;
	public GameObject orc6;
	public GameObject orc7;
	public GameObject orc8;
	public GameObject enemyEncounter;
	public GameObject arenaObject;
	public GameObject nextEventObject;
	public override IEnumerator EventCoroutine(){
		player.StopMovement();
		PlayAnimationPersistent(baddie,"IdleDown");
		PlayAnimationPersistent(orc1,"IdleDown");
		PlayAnimationPersistent(orc2,"IdleDown");
		PlayAnimationPersistent(orc3,"IdleDown");
		PlayAnimationPersistent(orc4,"IdleDown");
		PlayAnimationPersistent(orc5,"IdleDown");
		PlayAnimationPersistent(orc6,"IdleDown");
		PlayAnimationPersistent(orc7,"IdleDown");
		PlayAnimationPersistent(orc8,"IdleDown");
		yield return StartCoroutine(ShowDialogue("Intruder!", "Orc", orcHead));
		yield return StartCoroutine(ShowDialogue("Get him!", "Orc", orcHead));
		StartCoroutine(MoveObject(orc1,Direction.Left));
		StartCoroutine(MoveObject(orc2,Direction.Left));
		StartCoroutine(MoveObject(orc3,Direction.Left));
		StartCoroutine(MoveObject(orc4,Direction.Left));
		StartCoroutine(MoveObject(orc5,Direction.Left));
		StartCoroutine(MoveObject(orc6,Direction.Left));
		StartCoroutine(MoveObject(orc7,Direction.Left));
		yield return StartCoroutine(MoveObject(orc8,Direction.Left));
		StartCoroutine(MoveObject(orc1,Direction.Left));
		StartCoroutine(MoveObject(orc2,Direction.Left));
		StartCoroutine(MoveObject(orc3,Direction.Left));
		StartCoroutine(MoveObject(orc4,Direction.Left));
		StartCoroutine(MoveObject(orc5,Direction.Left));
		StartCoroutine(MoveObject(orc6,Direction.Left));
		StartCoroutine(MoveObject(orc7,Direction.Left));
		yield return StartCoroutine(MoveObject(orc8,Direction.Left));
		yield return StartCoroutine(ShowDialogue("No. Let him pass.", "?????", baddieHead));
		PlayAnimationPersistent(orc1,"IdleRight");
		PlayAnimationPersistent(orc2,"IdleRight");
		PlayAnimationPersistent(orc3,"IdleRight");
		PlayAnimationPersistent(orc4,"IdleRight");
		PlayAnimationPersistent(orc5,"IdleRight");
		PlayAnimationPersistent(orc6,"IdleRight");
		PlayAnimationPersistent(orc7,"IdleRight");
		PlayAnimationPersistent(orc8,"IdleRight");
		StartCoroutine(MoveObject(orc1,Direction.Right));
		StartCoroutine(MoveObject(orc2,Direction.Right));
		StartCoroutine(MoveObject(orc3,Direction.Right));
		StartCoroutine(MoveObject(orc4,Direction.Right));
		StartCoroutine(MoveObject(orc5,Direction.Right));
		StartCoroutine(MoveObject(orc6,Direction.Right));
		StartCoroutine(MoveObject(orc7,Direction.Right));
		yield return StartCoroutine(MoveObject(orc8,Direction.Right));
		StartCoroutine(MoveObject(orc1,Direction.Right));
		StartCoroutine(MoveObject(orc2,Direction.Right));
		StartCoroutine(MoveObject(orc3,Direction.Right));
		StartCoroutine(MoveObject(orc4,Direction.Right));
		StartCoroutine(MoveObject(orc5,Direction.Right));
		StartCoroutine(MoveObject(orc6,Direction.Right));
		StartCoroutine(MoveObject(orc7,Direction.Right));
		yield return StartCoroutine(MoveObject(orc8,Direction.Right));
		PlayAnimationPersistent(orc1,"IdleDown");
		PlayAnimationPersistent(orc2,"IdleDown");
		PlayAnimationPersistent(orc3,"IdleDown");
		PlayAnimationPersistent(orc4,"IdleDown");
		PlayAnimationPersistent(orc5,"IdleDown");
		PlayAnimationPersistent(orc6,"IdleDown");
		PlayAnimationPersistent(orc7,"IdleDown");
		PlayAnimationPersistent(orc8,"IdleDown");
		yield return StartCoroutine(ShowDialogue("Let me pass...?", "Mason", masonHead));
		yield return StartCoroutine(MoveObject(player.gameObject,Direction.Right));
		yield return StartCoroutine(MoveObject(player.gameObject,Direction.Right));
		yield return StartCoroutine(MoveObject(player.gameObject,Direction.Right));
		yield return StartCoroutine(MoveObject(player.gameObject,Direction.Right));
		yield return StartCoroutine(MoveObject(player.gameObject,Direction.Right));
		yield return StartCoroutine(ShowDialogue("Ahhh, Mason, you have made it. I am so happy to see you again.", "?????", baddieHead));
		yield return StartCoroutine(MoveCamera(new Vector3(2.5f,2.5f,-5.842f),2.0f));
		yield return StartCoroutine(ShowDialogue("Wait, you know me? Who are you?", "Mason", masonHead));
		yield return StartCoroutine(ShowDialogue("Of course I know you, Mason, why it was only just some months ago that-", "?????", baddieHead));
		yield return StartCoroutine(ShowDialogue("Ohhhh... Oh, I see. It has not happened for you yet.", "?????", baddieHead));
		yield return StartCoroutine(ShowDialogue("My apologies then, Mason, this must all be quite startling for you. Allow me to introduce myself.", "?????", baddieHead));
		yield return StartCoroutine(ShowDialogue("My name is Saddarr, and I owe everything I am, everything I have, to you.", "Saddarr", baddieHead));
		yield return StartCoroutine(ShowDialogue("You know what? I've changed my mind. I don't give a damn who you are or why you're doing this, but you're going to stop. Now.", "Mason", masonHead));
		yield return StartCoroutine(ShowDialogue("Stop? Why would I stop? We are so close to our goal now, we can not stop.", "Saddarr", baddieHead));
		yield return StartCoroutine(ShowDialogue("Whatever it is you're after, I'm not going to let you have it. Not like this.", "Mason", masonHead));
		yield return StartCoroutine(ShowDialogue("My, my, Mason. What has gotten into you? Is your goal truly not aligned with my own? How far must you have come from here?", "Saddarr", baddieHead));
		yield return StartCoroutine(ShowDialogue("I'm not going to say it again. Take your soldiers and leave.", "Mason", masonHead));
		yield return StartCoroutine(ShowDialogue("I must say, I am truly disappointed, Mason. I was very much looking forward to working with you. Oh well, I suppose it can not be helped. I can wait a while longer for you to become who I need you to be.", "Saddarr", baddieHead));
		yield return StartCoroutine(ShowDialogue("In the meantime, you are being troublesome, so you will understand that I need to remove you from this situation.", "Saddarr", baddieHead));
		yield return StartCoroutine(ShowDialogue("Remove him.", "Saddarr", baddieHead));
		StartCoroutine(MoveObject(orc1,Direction.Left));
		StartCoroutine(MoveObject(orc2,Direction.Left));
		StartCoroutine(MoveObject(orc3,Direction.Left));
		StartCoroutine(MoveObject(orc4,Direction.Left));
		StartCoroutine(MoveObject(orc5,Direction.Left));
		StartCoroutine(MoveObject(orc6,Direction.Left));
		StartCoroutine(MoveObject(orc7,Direction.Left));
		yield return StartCoroutine(MoveObject(orc8,Direction.Left));
		StartCoroutine(PlayAnimation(orc1,"ThrustLeft"));
		yield return StartCoroutine(PlayAnimation(orc2,"ThrustLeft"));
		DeleteObject(orc1);
		DeleteObject(orc2);
		StartBattle(enemyEncounter,arenaObject,gameObject,nextEventObject);
		EndEventCoroutine();
	}
}
